// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TutorSphere.Infrastructure.Persistence;

#nullable disable

namespace TutorSphere.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260821220000_ParentPaymentSplit")]
partial class ParentPaymentSplit
{
}
